pybind/pybind11_bazel

- BUILD
- CONTRIBUTING.md
- README.md
- build_defs.bzl
- py/BUILD.tpl
- python_configure.bzl
This adds the basic bazel rules needed to build pybind11 with Bazel.
A more complete example will be forthcoming in the pybind11_protobuf, which will include a full WORKSPACE file and the necessary bindings to use this.
> Add Bazel rules

- pybind11.BUILD
Is there any reason for eigen being hidden? No errors are being shown. I have this change in my mirror, and thought I would at least propose it upstream
> Expose eigen header. No explaination for why it was hidden

- build_defs.bzl
- pybind11.BUILD
I'm no expert in either Skylark or linkers, but here goes ...
This removes the hardcoded link option -Bsymbolic which is specific to GNU's linker when running on macOS.
Cheers,
Chris
> Add macOS linker compatibility

- build_defs.bzl
I want to statically link libstdc++ with the pybind extension and currently I can't because I can't pass in linker options.
> Allow users to pass in additional linkopts to pybind_extension

- build_defs.bzl
- pybind11.BUILD
See issue #3 for context
PR #10 appears to be using a deprecated method of detecting the platform that bazel is building for. Additionally, I'm not certain that `darwin` is a valid `cpu` option that can be detected automatically - my understanding was that `cpu` is for values like `x86` or `arm`, not `darwin` as darwin is an operating system.
Evidence:
[CPU flag documentation](https://docs.bazel.build/versions/master/user-manual.html#flag--cpu) (note the reference to CROSSTOOL): 
>This option specifies the target CPU architecture to be used for the compilation of binaries during the build.
>
>Note that a particular combination of crosstool version, compiler version, and target CPU is allowed only if it has been specified in the currently used CROSSTOOL file. 
[Examples of valid cpu …
> Modified select statement to be based on platforms, not `cpu` flag

- README.md
- build_defs.bzl
Right now, `pybind_extension` adds the `manual` tag to the underlying `cc_binary` rule. This tag prevents `bazel build //my/package/...` or `bazel build //my/package:all` from actually building the python extension. This behavior is unintuitive and removing the tag would greatly improve developer ergonomics and match the behavior that most people expect.
> Allow the python extension to be built by wildcards

- README.md
- py/BUILD.tpl
- pybind11.BUILD
- python_configure.bzl
This addition automatically runs python-config to retrieve the compiler and linker flags required to embed Python, and adds them to the copts and linkopts of a pybind11_embed target.
**Currently, only MacOS 10.13.3 tested and Python 3 supported**
Python environments tested:
- **pipenv 2018.11.26**
- **pyenv 1.2.16**
**Additions:**
- **`//python_configure.bzl`:**
- `_find_python_config()` function to find the local Python's python-config script. 
- `_get_embed_flags()` function to identify the copts and linkopts flags required to embed the Python interpreter.
- **`//py/BUILD.tpl`:**
- `cc_library(name= "python_embed")` combines python headers with embed flags.
- **`//pybind11.BUILD`:**
- `pybind11_embed target that depends on python_embed.`
**To embed the python interpreter, add …
> Initial commit to add embedding support via pybind11_embed target

- python_configure.bzl
Add a `python3` boolean argument to `python_configure`. If set to True, the Python installation will be auto-detected by running `which python3`, so Python 3 will be used. If False (default), the Python installation will be detected with `which python`, which will use either Python 2 or Python 3 depending on what `python` points to (this is the old behavior).
Fixes https://github.com/pybind/pybind11_bazel/issues/16.
> Support building against Python 3

- README.md
- python_configure.bzl
Allow `python_configure` to use a Python interpreter that is provided by a Bazel target, similarly to other Python rules (e.g. [`pip_install`](https://github.com/bazelbuild/rules_python/tree/master/python/pip_install#setup-workspace)).
> Add support for hermetic Python

- python_configure.bzl
Fixes Google-internal pybind11_abseil testing.
> Adopting Python 3.10 compatibility change by @jblespiau

- python_configure.bzl
- We use the binary to find the version of Python
- For Python 3.10 and greater, we use `import sysconfig; print(sysconfig.get_path('include'))` to get the include path.
> Fix the automatic detection of the include directory for Python 3.10

- python_configure.bzl
The error message about not finding the python binary PYTHON_BIN_PATH that is --define'ed was confusing: --define does not work, but --repo_env does.
Maybe this worked in older bazel versions ? (I am using bazel 5.2).
> Update setting PYTHON_BIN_PATH message --define -> --repo_env

- py/BUILD.tpl
> Support 32-bit Python/Windows by using `@platforms`.

- build_defs.bzl
Fixes https://github.com/pybind/pybind11_bazel/issues/57.
> Explicitly specify `-undefined dynamic_lookup`

- python_configure.bzl
* Local always results in true.
* Unclear why the flag is useful in this case.
* Currently impedes builds using bazel RBEs.
> Remove local flag.

- build_defs.bzl
In case, attributes such as the visibility are set, this is not available for the alias. Passing the `kwargs` to the `alias` as well should fix this.
> Forward kwargs to alias

- build_defs.bzl
Convert some comments into docstrings to better leverage buildifier and allow for documentation generation eventually.
> Convert comments into docstrings

- build_defs.bzl
If the user's toolchain / global settings imply -z,defs, this is necessary similar to the macOS flags to allow libpython symbols to be undefined
> Add -Wl,-z,undefs to linux links

- MODULE.bazel
Latest release available is https://github.com/pybind/pybind11/releases/tag/v2.13.1 so let's make it available for bazel as well.
> Bump pybind version to 2.13.1

- examples/basic/MODULE.bazel
This is not required since the local version is used
> Bump rules_python version in example

- build_defs.bzl
Reverts pybind/pybind11_bazel#90 which introduced https://github.com/pybind/pybind11_bazel/issues/94 causing also issues for https://github.com/pybind/pybind11_abseil. The revert closes #94.
> Revert "Add -Wl,-z,undefs to linux links"

- MODULE.bazel
- internal_configure.bzl
Fixes https://github.com/pybind/pybind11_bazel/issues/102
> Get module version from module_ctx and try to lookup integrities

- pybind11-BUILD.bazel
See https://github.com/pybind/pybind11/pull/5664 for context.
> Remove -Wno-undefined-inline

- MODULE.bazel
- internal_configure.bzl
This avoids an unnecessary lockfile entry.
> Mark module extension as reproducible

- .github/workflows/amd64_linux_bazel.yml
- .github/workflows/amd64_macos_bazel.yml
- .github/workflows/amd64_windows_bazel.yml
- .github/workflows/arm64_macos_bazel.yml
- examples/basic/.bazelrc
- examples/basic/BUILD.bazel
- examples/embed/.bazelrc
- examples/embed/BUILD.bazel
- examples/embed/MODULE.bazel
- examples/embed/embed.cc
> Add embed example
